### PR TITLE
Use double quotes for inner string

### PR DESCRIPTION
**Pull request by zxc23**
The single quotes were giving me red underlines in VSC.

### CODE REVIEW

**Comment by SimulatedGREG** [comment]
This is proper syntax to for the `standard` set of rules. When the boilerplate is fully scaffolded, the extra templating resolves this issue. No need to update this. Thanks for the contribution.

**Comment by zxc23** [comment]
What do you mean by fully scaffolding the boilerplate? I made a new electron-vue project and checked index.ejs and it had the issue. 

Looks like this for me:

```
  <head>
    <meta charset="utf-8">
    <title>my-project</title>
    <% if (htmlWebpackPlugin.options.nodeModules) { %>
      <!-- Add `node_modules/` to global paths so `require` works properly in development -->
      <script>
        require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>')
      </script>
    <% } %>
  </head>
```

**Comment by SimulatedGREG** [comment]
Oh sorry, I meant to say when the EJS template is compiled within the `html-webpack-plugin`. Most text editors treat template languages like EJS the same as if it were a HTML file. Because of this behavior, they are technically *valid HTML*, there will always be syntax errors.

**Comment by zxc23** [comment]
Alright, thanks for that.

**Pull request closed without merging**
