### PR TITLE
Fix Vue Accessories scripts.

### PR DESCRIPTION
**Pull request by liril-net**

### CODE REVIEW

**Comment by SimulatedGREG** [comment]
From what I can see from the commits you made, this setup should fix everything, but you also need to escape any instances of template `{{variables}}`. Doing a fresh scaffold on your fork yeilds `  .replace(//g, routeName)
` on line 27 of `tasks/vue/route.js`. Its a simple fix, and here's a reference to how vue template variables are escaped...

https://github.com/SimulatedGREG/electron-vue/blob/master/template/app/src/renderer/components/LandingPageView/Versions.vue#L3

**Comment by liril-net** [comment]
@SimulatedGREG I have wrote down a template function to escape variables.

Besides, i think it a better idea to create `index.vue` in `FooView` directory to keep a clean structure. And i have found that if we want a better *Accessories* , we should parse the file to get the real structure of routes.

**Comment by SimulatedGREG** [comment]
> Besides, i think it a better idea to create index.vue in FooView directory to keep a clean structure. 

I actually really like this idea, a lot.

> ...we should parse the file to get the real structure of routes.

This is part of why I was leaning towards removing this feature. I don't really know of any methods to do such a task.

**Comment by liril-net** [comment]
It is hard to implement some scripts to cover all situations, so may be it is not so bad to remove this feature. So that you can expand more energy on scripts about building progress.

**Comment by SimulatedGREG** [comment]
Yeah, but I'm still considering the `index.vue` idea. Thanks for your contribution.

**Pull request closed without merging**
