### PR TITLE
Update vue-loader version

### PR DESCRIPTION
**Pull request by snovey**
Update vue-loader version and support the new version of postcss-nesting.

### CODE REVIEW

**Comment by snovey** [comment]
Ok……
However, if do not upgrade the vue-loader version, when using the nested syntax in the postcss will encounter problems, only by manually modifying the vue-loader dependent package version or upgrade vue-loader to solve this problem.

**Comment by SimulatedGREG** [comment]
I'm not against updating `vue-loader`; just wanting you to remove the routes change. If not, I'll manually update myself.

**Comment by snovey** [comment]
I have removed the routes change, please review.

**Comment by snovey** [comment]
CI failed because: 
> Error: Failed to find Electron v1.8.0 for linux-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-linux-x64.zip

And I do not think it's caused by my change.
But how to solve this problem?  I am not familiar with CI.

**Comment by SimulatedGREG** [comment]
CI test failure is unrelated to you. Ignore it.

**Pull request merged**
