### PR TITLE
update .eslintrc.js for support async/await default

### PR DESCRIPTION
**Pull request by TennyZhuang**
add ecmaVersion option and set to 8

### CODE REVIEW

**Comment by SimulatedGREG** [comment]
What exactly is "asyncio"?

**Comment by TennyZhuang** [comment]
async/await

**Comment by SimulatedGREG** [comment]
Is there any specific reason why this would need to be defined, considering `babel-preset-stage-0` already fills in the gap?

**Comment by TennyZhuang** [comment]
if I close the eslint, it works well with async/await. but the code cannot pass the eslint.

when I `npm run dev`, the error was

77859fdd-d0d8-4021-93bc-4b5439caeeb6

because the eslint seems not support such grammar, so declaring the `ecmaVersion` in eslintrc is needed.

**Comment by SimulatedGREG** [comment]
After investigation, it seems `eslint` core doesn't fully know how to handle all new ECMAScript features. Yes, setting `ecmaVersion` to `8` does fix your situation, but I will be changing the parser to use `babel-eslint`. Closing and will push out a fix soon.

**Pull request closed without merging**
