### PR TITLE
修复 ReferenceError: process is not defined 问题

### PR DESCRIPTION
**Pull request by wjf2016**

### CODE REVIEW

**Comment by subins2000** [comment]
Thank you. This solves the error. Errors started happening when I upgraded electron

**Comment by legendforfree** [comment]
## fixed
> you can add these text with `.electron-vue/webpack.web.config.js` and `.electron-vue/webpack.renderer.config.js` file,in HtmlWebpackPlugin.
```
      templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      },
```

**Comment by zjfresh** [comment]
It helps for me. Thanks a lot

**Comment by tsflow** [comment]
why not merge this pull requesst？its very useful

**Pull request merged**
