### PR TITLE
 Add support for web output ($npm run pack:web).

### PR DESCRIPTION
**Pull request by utkukaratas**
2 seperate commits as I had to touch the renderer config ("app/src/renderer" to "app/src" business). Please let me know if that was a bad idea indeed.

### CODE REVIEW

**Comment by SimulatedGREG** [comment]
It seems a little odd to have `app/src/web/main.js`, and then use `app/src/renderer` for the actual app. Why not just use an environment variable to describe the target platform?

**Comment by utkukaratas** [comment]
The restructure looks great! I'll reopen the case once that branch is ready.

Just for the sake of learning though... is there any example of doing this via env vars in the source? 

(Probably I'm missing something. The env var solution sounds worse to me as it would mean turning main.js into another template resource [like index.ejs] which further implicates things.)

**Comment by alex-ketch** [comment]
I gave this setup a try with the simplified structure, but ran into an error.
With the default LandingPageView, UglifyJS throws an error because of some calls to Electron and Node versions in `Versions.vue` file. After removing those, it compiles just fine.

Just something to consider.
Thanks for the great work otherwise!

**Comment by SimulatedGREG** [comment]
Web output has landed in the `dev` branch! Check #171 for more info. Closing.

**Pull request closed without merging**
